version: '2.1'

services:
  pizza_app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./pizza:/pizza
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

