# Generated by Django 2.1.4 on 2019-01-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzas', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_state', models.CharField(default='A', max_length=1, verbose_name='Order status')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='customers.Customers')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number_of_pizzas', models.SmallIntegerField(verbose_name='Number of pizzas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('pizza_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzas.Pizzas')),
                ('pizza_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzas.PizzaSizes')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
